server.port: 12200
server.tomcat:
  max-http-form-post-size: 500MB
  max-swallow-size: 150MB
spring.servlet.multipart:
  max-request-size: 500MB
  max-file-size: 500MB

# HTTP Server Settings
server.ssl:
  enabled: true
  client-auth: none
  key-store: classpath:config/localhost.p12
  trust-store: classpath:config/truststore.p12

# HTTP Client Settings
http.client.ssl:
  # Application (Microservice Family) Client Certificate
  key-store: classpath:/config/clientmservocp-dev.oskarmobil.cz.p12
  # Includes VFCZ Root CA, VFCZ AO SubCA, May Include ldaps.oskarmobil.cz Certificate
  trust-store: classpath:/config/truststore.p12

spring:
  jackson:
    serialization:
      indent-output: true

logging.level:
  cz: debug
#  org.apache.kafka.metadata.authorizer: trace
#  kafka.authorizer.logger: trace
#  kafka.server.metadata.BrokerMetadataPublisher: trace
#  org.apache.kafka.common.network: trace

# APPLICATION specific settings
kafka:
  client:
    "[bootstrap.servers]": localhost:${kafka.server-mandatory.client-broker-port}
    "[ssl.keystore.location]": ${server.ssl.key-store}
    "[ssl.keystore.password]": ${server.ssl.key-store-password}
    "[ssl.keystore.type]": PKCS12
    "[ssl.truststore.location]": ${server.ssl.trust-store}
    "[ssl.truststore.password]": ${server.ssl.trust-store-password}
    "[ssl.truststore.type]": PKCS12
    "[security.protocol]": SASL_SSL
    "[sasl.mechanism]": SCRAM-SHA-512
    "[sasl.jaas.config]": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${kafka.super-user.name}\" password=\"${kafka.super-user.password}\";"

  server-mandatory:
    node-id-mapping:
      localhost: 0
    controller-port: 12204
    client-broker-port: 12202
    inter-broker:
      port: 12203

  server:
    "[num.partitions]": 1
    "[offsets.topic.replication.factor]": 1
    "[log.dirs]": ${java.io.tmpdir}/kafka-data
    "[metadata.log.dir]": ${java.io.tmpdir}/kafka-metadata
    "[controller.quorum.voters]": 0@localhost:${kafka.server-mandatory.controller-port}
