# Management Endpoint Security Settings
spring.security.user:
  name: user
  password: password

# HTTP Server Settings
server.ssl:
  # Server Certificate
  key-store-password: 'changeit'
  # Includes VFCZ Root CA, VFCZ AO SubCA, May Include ldaps.oskarmobil.cz Certificate
  trust-store-password: 'changeit'

# HTTP Client Settings
http.client.ssl:
  # Application (Microservice Family) Client Certificate
  key-store-password: "XYGkF1EQS9ag"
  # Includes VFCZ Root CA, VFCZ AO SubCA, May Include ldaps.oskarmobil.cz Certificate
  trust-store-password: 'changeit'

security.oauth2.resource.jwt.keyValue: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnTMvnNtrXm22jbNA26IrDmzjHk61JvVCI275fyBIJ96QwHx+agyb4q4nAxQdeL45Lr54LovTXXwMPXsIluccOySrsy+HQ51JbZFD2vCeIYoFMi6j8BY8kQveHMrCYv3SMOQtQTEOe1O7irip1F9aYAyw0agbZzsQxVilGc6MYzyzJm8HDZIAhKwXo3vtsoLwzZU63DuMF5iny7keuaK3t2AUGYo+LrhFkd7pmhIVicXCwHbNgKtii9bzQF5+zOHhlVSQdZqnChjSdHbX3H2kOcdop1I0DMv9DPC5HYgcIX8Ab8zZvevv3EdMYdH+yltZxRbuhUKhzO/g1kHBB9udaQIDAQAB
  -----END PUBLIC KEY-----

# APPLICATION specific settings
kafka:
  server-mandatory:
    inter-broker:
      # certificate distinguished name, certificate used for internal-communication between brokers and controllers
      dn: L=Prague,CN=ocp-kafka,OU=IT,O=Oskar a.s.,C=CZ
      # certificate used for internal-communication between brokers and controllers
      certificate:
        key-store: classpath:/config/kafka.p12
        key-store-password: changeit
  super-user:
    name: kafkasupervisor
    password: kafkasupervisor123
